theme: jekyll-theme-cayman
show_downloads: true
description: "Image Inpainting for a Dynamic Objects Invariant Space <br> Berta Bescos, Jose Neira, Roland Siegwart, Cesar Cadena"
logo: #/assets/img/logo.png
